package test.com.kbconnect.boundary;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.hamcrest.CoreMatchers;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CustomerRegistrationLoginSeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newCustomerRegistAndLoginWithSelenium() {
    driver.get("http://localhost:8080/KBPayment_GroupProject/login.jsp");
    driver.manage().window().setSize(new Dimension(1216, 678));
    driver.findElement(By.linkText("new User.")).click();
    driver.findElement(By.name("fullName")).click();
    driver.findElement(By.name("fullName")).sendKeys("TESTING FULLNAME");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("alchemist");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("csis3275kbconnect@gmail.com");
    driver.findElement(By.cssSelector(".row:nth-child(2)")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.name("DOB")).click();
    driver.findElement(By.name("DOB")).sendKeys("2020-03-30");
    driver.findElement(By.cssSelector(".row:nth-child(4)")).click();
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("Royal Ave");
    driver.findElement(By.cssSelector(".button-primary")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("alchemist");
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.name("password")).sendKeys("password");
    driver.findElement(By.cssSelector(".button-primary:nth-child(5)")).click();
    

	String valueOfUsername = driver.findElement(By.cssSelector(".list-group-item:nth-child(1)")).getText();
	assertThat(valueOfUsername, is("Username: alchemist"));

	String valueOfAddress = driver.findElement(By.cssSelector(".list-group-item:nth-child(4)")).getText();
	assertThat(valueOfAddress, is("Address: Royal Ave"));
      
	String valueOfEmail = driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).getText();
	assertThat(valueOfEmail, is("Email: csis3275kbconnect@gmail.com"));
  }
}
